version: '3'

services:

  cache-srv:
    image: registry.eshop.com/eshop/cache-srv:${TAG}
    container_name: cache-srv
    ports:
      - "8006:8006"
    environment:
      - spring.cloud.config.profile=local
      - spring.cloud.config.uri=http://13.236.71.227:9999
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro
      - /etc/localtime:/etc/localtime:ro
  user-srv:
    image: registry.eshop.com/eshop/user-srv:${TAG}
    container_name: user-srv
    ports:
      - "7005:7005"
    environment:
      - spring.cloud.config.profile=local
      - spring.cloud.config.uri=http://13.236.71.227:9999
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro
      - /etc/localtime:/etc/localtime:ro
  user-api:
    image: registry.eshop.com/eshop/user-api:${TAG}
    container_name: user-api
    ports:
      - "2222:2222"
    environment:
      - spring.cloud.config.profile=local
      - spring.cloud.config.uri=http://13.236.71.227:9999
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro
      - /etc/localtime:/etc/localtime:ro
  operate-api:
    image: registry.eshop.com/eshop/operate-api:${TAG}
    container_name: operate-api
    ports:
      - "3333:3333"
    environment:
      - spring.cloud.config.profile=local
      - spring.cloud.config.uri=http://13.236.71.227:9999
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai:ro
      - /etc/localtime:/etc/localtime:ro